### Get an image
GET http://localhost:3000/images/favicon.png



### Get all books
GET http://localhost:3000/api/books?sortBy=title&author=франко

### Get a book
GET http://localhost:3000/api/books/6

### Get a book Franko
GET http://localhost:3000/api/books?author=франко

### Get a author book
GET http://localhost:3000/api/authors/42/books/2

### Add new book
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "Кобзар",
  "author": "Тарас Шевченко"
}

### Add new book
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "Лісова пісня",
   "author": "Леся Українка"
}

### Update book
PATCH http://localhost:3000/api/books/2
Content-Type: application/json

{
  "title": "Захар Беркут (перевидання)"
}

### Replace book completely
PUT http://localhost:3000/api/books
Content-Type: application/json

{
  "title": "Кобзар",
  "author": "Тарас Шевченко",
  "year": 1840
}

### Delete book
DELETE http://localhost:3000/api/books

